car:
  profile: D:/car/uploadPath

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/cm?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  # 模板引擎 
  thymeleaf:
    mode: HTML 
    encoding: utf-8
    # 禁用缓存 
    cache: false




mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.carmanage.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



server:
  port: 7080
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
